# Generated by Django 6.0.3 on 2026-04-16 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=512)),
                ('source', models.CharField(blank=True, choices=[('file', 'File upload'), ('url', 'Web page URL'), ('text', 'Pasted text')], default='', max_length=16)),
                ('embedding_status', models.CharField(choices=[('pending', 'Pending'), ('indexed', 'Indexed'), ('stale', 'Stale')], default='pending', max_length=16)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Processed Document',
                'verbose_name_plural': 'Processed Documents',
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('resilience_factor', models.CharField(blank=True, db_index=True, max_length=64)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='rag_pipeline.document')),
            ],
            options={
                'verbose_name': 'Document Chunk',
                'verbose_name_plural': 'Document Chunks',
                'ordering': ['chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=512)),
                ('source_type', models.CharField(choices=[('file', 'File upload'), ('url', 'Web page URL'), ('text', 'Pasted text')], max_length=16)),
                ('resilience_factor', models.CharField(blank=True, db_index=True, help_text='Resilience factor this source relates to (e.g. family_support)', max_length=64)),
                ('category', models.CharField(blank=True, choices=[('interventions', 'Interventions'), ('active_ingredients', 'Active Ingredients'), ('evidence_base', 'Evidence Base'), ('resources', 'Resources')], help_text='Type of content in this source', max_length=64)),
                ('file', models.FileField(blank=True, upload_to='raw_sources/')),
                ('url', models.URLField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_source', to='rag_pipeline.document')),
            ],
            options={
                'verbose_name': 'Raw Knowledge Base Source',
                'verbose_name_plural': 'Raw Knowledge Base Sources',
            },
        ),
    ]
