# Generated by Django 6.0.3 on 2026-04-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchunk',
            name='resilience_factor',
            field=models.CharField(blank=True, choices=[('family_support', 'Family Support'), ('optimism', 'Optimism'), ('goal_directedness', 'Goal-Directedness / Coping'), ('social_connections', 'Social Connections'), ('health', 'Health')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='knowledgesource',
            name='resilience_factor',
            field=models.CharField(blank=True, choices=[('family_support', 'Family Support'), ('optimism', 'Optimism'), ('goal_directedness', 'Goal-Directedness / Coping'), ('social_connections', 'Social Connections'), ('health', 'Health')], db_index=True, max_length=64),
        ),
    ]
