# Generated by Django 6.0.3 on 2026-04-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='resilience_factor',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
