# Generated by Django 6.0.3 on 2026-03-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rag_pipeline", "0002_documentchunk_knowledgesource_alter_document_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentchunk",
            options={
                "ordering": ["chunk_index"],
                "verbose_name": "Document Chunk",
                "verbose_name_plural": "Document Chunks",
            },
        ),
        migrations.RemoveIndex(
            model_name="documentchunk",
            name="document_embedding_idx",
        ),
        migrations.RenameField(
            model_name="document",
            old_name="embedded_at",
            new_name="indexed_at",
        ),
        migrations.AddField(
            model_name="document",
            name="embedding_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("indexed", "Indexed"), ("stale", "Stale")],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="chunk_index",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name="documentchunk",
            name="embedding",
        ),
    ]
