# Generated by Django 6.0.4 on 2026-04-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_pipeline', '0002_alter_documentchunk_resilience_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='implementation_difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, max_length=16),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='target_resilience_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, max_length=16),
        ),
    ]
