# Generated by Django 6.0.3 on 2026-04-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_pipeline', '0002_documentchunk_resilience_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgesource',
            name='category',
            field=models.CharField(blank=True, choices=[('interventions', 'Interventions'), ('active_ingredients', 'Active Ingredients'), ('evidence_base', 'Evidence Base'), ('resources', 'Resources')], help_text='Type of content in this source', max_length=64),
        ),
        migrations.AddField(
            model_name='knowledgesource',
            name='resilience_factor',
            field=models.CharField(blank=True, db_index=True, help_text='Resilience factor this source relates to (e.g. family_support)', max_length=64),
        ),
    ]
