# Generated by Django 6.0.3 on 2026-03-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rag_pipeline", "0003_alter_documentchunk_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[("file", "File upload"), ("url", "Web page URL"), ("text", "Pasted text")],
                default="",
                max_length=16,
            ),
        ),
    ]
