# Generated by Django 6.0.3 on 2026-04-15 06:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilience_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=128)),
                ('teacher_email', models.EmailField(max_length=254)),
                ('forms_completed', models.PositiveIntegerField()),
                ('rating', models.PositiveSmallIntegerField()),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='analysisrequest',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='report_emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='teacher_email',
            field=models.EmailField(default='placeholder@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('consent_form', 'Consent + form'), ('report_ready', 'Report ready'), ('feedback_request', 'Feedback request')], max_length=32)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('attachment_path', models.CharField(blank=True, max_length=512)),
                ('dedupe_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('analysis_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='resilience_app.analysisrequest')),
            ],
            options={
                'ordering': ('scheduled_at', 'pk'),
            },
        ),
    ]
