# Generated by Django 6.0.4 on 2026-04-19 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilience_app', '0003_add_consent_form_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=128, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_given_at', models.DateTimeField(blank=True, null=True)),
                ('completed_screenings_count', models.PositiveIntegerField(default=0)),
                ('feedback_status', models.CharField(choices=[('pending', 'Pending'), ('declined', 'Declined'), ('submitted', 'Submitted')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='scores',
            field=models.JSONField(help_text='Dict of factor_key -> list/dict of scores (0/1/2/NA)'),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='teacher_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_requests', to='resilience_app.teacherprofile'),
        ),
    ]
