# Generated by Django 6.0.3 on 2026-04-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilience_app', '0007_teacherappfeedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherappfeedback',
            options={'verbose_name': 'Teacher App Feedback', 'verbose_name_plural': 'Teacher App Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={'verbose_name': 'Teacher Profile', 'verbose_name_plural': 'Teacher Profiles'},
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='sources',
            field=models.JSONField(blank=True, default=list, help_text='List of sources used for recommendations'),
        ),
    ]
